workflows:
  android-apk-build:
    name: Build 0003 Player APK
    max_build_duration: 30
    instance_type: mac_mini_m2
    scripts:
      - name: Setup Environment & Build Release APK
        script: |
          # 1. ساخت فایل‌های .env جهت جلوگیری از خطای Plugin
          touch .env.example
          touch .env

          # 2. ساخت یک کلید امضای رسمی، نو و 100% سالم مستقیماً روی سرور
          keytool -genkeypair -v \
            -keystore my-upload-key.jks \
            -alias upload \
            -keypass ali13821382ali \
            -storepass ali13821382ali \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Ali Ziaee, OU=0003, O=0003 Player, L=Tehran, ST=Tehran, C=IR"

          # 3. دانلود و تنظیم Gradle
          curl -sL https://services.gradle.org/distributions/gradle-9.3.1-bin.zip -o gradle-9.3.1-bin.zip
          unzip -q gradle-9.3.1-bin.zip
          export PATH=$(pwd)/gradle-9.3.1/bin:$PATH

          # 4. بیلد نهایی Release با همان کلید
          gradle assembleRelease
    artifacts:
      - "**/build/outputs/apk/release/*.apk"
